DROP TABLE IF EXISTS ForumMessage;
DROP TABLE IF EXISTS BookClubMessage;
DROP TABLE IF EXISTS HasBook;
DROP TABLE IF EXISTS Forum;
DROP TABLE IF EXISTS Message;
DROP TABLE IF EXISTS bookclubregistration;
DROP TABLE IF EXISTS BookExchange;
DROP TABLE IF EXISTS BookClub;
DROP TABLE IF EXISTS Book;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS lookingToExchange;
DROP TABLE IF EXISTS exchangeActions;



DROP TRIGGER IF EXISTS forum_spoiler_update;
DROP TRIGGER IF EXISTS book_exchange_update;
DROP TRIGGER IF EXISTS book_availability_update;
